unstable_features = true
max_width = 120

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"

# will be available starting in version 2 of rustfmt
# group_imports = "StdExternalCrate"

use_field_init_shorthand = true

match_block_trailing_comma = true

wrap_comments = true
comment_width = 110
